// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    PageContainer: typeof import("./src/components/pageContainer/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VanButton: typeof import("vant/es")["Button"];
    VanConfigProvider: typeof import("vant/es")["ConfigProvider"];
    VanField: typeof import("vant/es")["Field"];
    VanForm: typeof import("vant/es")["Form"];
    VanNavBar: typeof import("vant/es")["NavBar"];
    VanStep: typeof import("vant/es")["Step"];
    VanSteps: typeof import("vant/es")["Steps"];
  }
}
